### ISSUE TITLE
Anything that could use some help?

### ISSUE THREAD

**Issue by redwire** [s-rah/go-ricochet#1]
Hi there!
It's really cool to see someone working on an implementation of this protocol in Go.
I've got a lot of experience writing Go now and would love to try to land a couple PRs on this project if there's anything you think you could use help with.
Documentation? Unit tests? Features?

Let me know if there's anything available.
Cheers!

**Comment by s-rah** [comment]
Hey! Yes there is so much to do :) The code is littered with Todos and non existent error handling - those need fixing. More consistent interfaces (one function for Connect, another for Auth and a ConnectAndAuth function). 

And as you said. Docs and tests are always welcome :)

**Comment by s-rah** [comment]
Hey Again, I've thrown up some ideas and TODO's  in the Issues #2 #3 #4 #5 #6. Feel free to have a poke around, or dive into something else entirely. :)  Closing this in favor of those issues. Thanks!
