### ISSUE TITLE
As a Developer I want to be able to define & use new Channels for my application

### ISSUE THREAD

**Issue by s-rah** [s-rah/go-ricochet#19]
# Deliverables

* A new example application that defines & uses a new channel type (file exchange?)
* Automated tests showing 2 services exchanging new channel messages & demonstrating a fall back when engaging with standard ricochet (a negotiation / usage error).

Part of implementing #18 - this is a nice high level goal which is going to need lots of the underlying work complete to achieve.

**Comment by psycik** [comment]
File transfer would be really great for this! I wish I had some free time to help but help up the good work.
