### ISSUE TITLE
Rename This Project

### ISSUE THREAD

**Issue by s-rah** [s-rah/go-ricochet#35]
Having https://github.com/ricochet-im/ricochet-go and `go-ricochet` is confusing in text and impossible to have easy to follow discussions with outloud.

Possible candidates for a name:

* `ricochet-protocol`
* `libRicochet`

I'm open to other suggestions.

**Comment by bmintz** [comment]
~~*g*unshot~~

**Comment by n8fr8** [comment]
ricochet-core-go
libricochet-go

**Comment by lapsedordinary** [comment]
riGochet is too obvious, isn't it?

**Comment by Benevolent** [comment]
+1 for libricochet-go
That is how signal does it as well

**Comment by s-rah** [comment]
libricochet-go wins, moved to OpenPrivacy repository https://git.openprivacy.ca/openprivacy/libricochet-go
