### ISSUE TITLE
Interested in a QT ui?

### ISSUE THREAD

**Issue by lostinblue** [s-rah/go-ricochet#7]
I could start building a QT or even gtk UI if you would be willing to accept one. I would need a similar but different one for something I'm currently building that also uses ricochet in golang. I could also do a webkit UI.

**Comment by s-rah** [comment]
Hey :)  

I'm not sure if go-ricochet should have a UX, the main intention is to provide an easy way to integrate ricochet into other application. The thought has crossed my mind to pull this into another project to build a ricochet client in go, although I don't have the time to manage something like that.

That being said https://github.com/s-rah/recoil is a testing tool I wrote from ricochet, which I think it would be really cool to have a UI for - if you would be interested? :)

**Comment by lostinblue** [comment]
I will check it out, if I can put something together I will glady contribute. 

I understand with not wanting this project to expand beyond the scope you have the time to manage. Thanks for putting this together.
